SPECIAL>LOADMODEL|"EPS.mdl"

SIMULATE>SAVELIST|OutputVarsToExport.lst
SIMULATE>RUNNAME|NoSettings
SIMULATE>READCIN|
MENU>RUN|O
MENU>VDF2TAB|NoSettings.vdfx|NoSettings.tsv|OutputVarsToExport.lst|+!||2019|2050|:NoSettings
FILE>DELETE|NoSettings.vdfx

SIMULATE>SAVELIST|
